name: PSCompression Workflow
on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

  release:
    types:
    - published

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  BUILD_CONFIGURATION: ${{ fromJSON('["Debug", "Release"]')[startsWith(github.ref, 'refs/tags/v')] }}

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build module - Debug
      shell: pwsh
      run: ./build.ps1 -Configuration $env:BUILD_CONFIGURATION -Task Build
      if: ${{ env.BUILD_CONFIGURATION == 'Debug' }}

    - name: Build module - Publish
      shell: pwsh
      run: ./build.ps1 -Configuration $env:BUILD_CONFIGURATION -Task Build
      if: ${{ env.BUILD_CONFIGURATION == 'Release' }}

    - name: Capture PowerShell Module
      uses: actions/upload-artifact@v3
      with:
        name: PSModule
        path: output/*.nupkg

  publish:
    name: publish
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
    - build
    runs-on: windows-latest
    steps:
    - name: Restore Built PowerShell Module
      uses: actions/download-artifact@v3
      with:
        name: PSModule
        path: ./

    - name: Publish to Gallery
      if: github.event_name == 'release'
      shell: pwsh
      run: >-
        dotnet nuget push '*.nupkg'
        --api-key $env:PSGALLERY_TOKEN
        --source 'https://www.powershellgallery.com/api/v2/package'
        --no-symbols
      env:
        PSGALLERY_TOKEN: ${{ secrets.PSGALLERY_TOKEN }}
